/**
 * Currencies users can pick for ingredient / recipe costing.
 * Subscription paywall stays USD (App Store / Play local pricing is separate).
 */
export const CURRENCIES = [
  { code: 'USD', symbol: '$', label: 'US Dollar' },
  { code: 'EUR', symbol: '€', label: 'Euro' },
  { code: 'GBP', symbol: '£', label: 'British Pound' },
  { code: 'INR', symbol: '₹', label: 'Indian Rupee' },
  { code: 'AUD', symbol: 'A$', label: 'Australian Dollar' },
  { code: 'CAD', symbol: 'C$', label: 'Canadian Dollar' },
  { code: 'NZD', symbol: 'NZ$', label: 'New Zealand Dollar' },
  { code: 'SGD', symbol: 'S$', label: 'Singapore Dollar' },
  { code: 'HKD', symbol: 'HK$', label: 'Hong Kong Dollar' },
  { code: 'JPY', symbol: '¥', label: 'Japanese Yen' },
  { code: 'CNY', symbol: '¥', label: 'Chinese Yuan' },
  { code: 'KRW', symbol: '₩', label: 'South Korean Won' },
  { code: 'THB', symbol: '฿', label: 'Thai Baht' },
  { code: 'MYR', symbol: 'RM', label: 'Malaysian Ringgit' },
  { code: 'IDR', symbol: 'Rp', label: 'Indonesian Rupiah' },
  { code: 'PHP', symbol: '₱', label: 'Philippine Peso' },
  { code: 'VND', symbol: '₫', label: 'Vietnamese Dong' },
  { code: 'AED', symbol: 'د.إ', label: 'UAE Dirham' },
  { code: 'SAR', symbol: '﷼', label: 'Saudi Riyal' },
  { code: 'QAR', symbol: 'ر.ق', label: 'Qatari Riyal' },
  { code: 'KWD', symbol: 'د.ك', label: 'Kuwaiti Dinar' },
  { code: 'BHD', symbol: 'BD', label: 'Bahraini Dinar' },
  { code: 'OMR', symbol: 'ر.ع.', label: 'Omani Rial' },
  { code: 'ILS', symbol: '₪', label: 'Israeli Shekel' },
  { code: 'TRY', symbol: '₺', label: 'Turkish Lira' },
  { code: 'ZAR', symbol: 'R', label: 'South African Rand' },
  { code: 'NGN', symbol: '₦', label: 'Nigerian Naira' },
  { code: 'KES', symbol: 'KSh', label: 'Kenyan Shilling' },
  { code: 'EGP', symbol: 'E£', label: 'Egyptian Pound' },
  { code: 'GHS', symbol: 'GH₵', label: 'Ghanaian Cedi' },
  { code: 'MAD', symbol: 'د.م.', label: 'Moroccan Dirham' },
  { code: 'BRL', symbol: 'R$', label: 'Brazilian Real' },
  { code: 'MXN', symbol: 'MX$', label: 'Mexican Peso' },
  { code: 'ARS', symbol: 'AR$', label: 'Argentine Peso' },
  { code: 'CLP', symbol: 'CL$', label: 'Chilean Peso' },
  { code: 'COP', symbol: 'COL$', label: 'Colombian Peso' },
  { code: 'PEN', symbol: 'S/', label: 'Peruvian Sol' },
  { code: 'CHF', symbol: 'CHF', label: 'Swiss Franc' },
  { code: 'SEK', symbol: 'kr', label: 'Swedish Krona' },
  { code: 'NOK', symbol: 'kr', label: 'Norwegian Krone' },
  { code: 'DKK', symbol: 'kr', label: 'Danish Krone' },
  { code: 'PLN', symbol: 'zł', label: 'Polish Złoty' },
  { code: 'CZK', symbol: 'Kč', label: 'Czech Koruna' },
  { code: 'HUF', symbol: 'Ft', label: 'Hungarian Forint' },
  { code: 'RON', symbol: 'lei', label: 'Romanian Leu' },
  { code: 'RUB', symbol: '₽', label: 'Russian Ruble' },
  { code: 'UAH', symbol: '₴', label: 'Ukrainian Hryvnia' },
  { code: 'TWD', symbol: 'NT$', label: 'New Taiwan Dollar' },
  { code: 'PKR', symbol: '₨', label: 'Pakistani Rupee' },
  { code: 'BDT', symbol: '৳', label: 'Bangladeshi Taka' },
  { code: 'LKR', symbol: 'Rs', label: 'Sri Lankan Rupee' },
  { code: 'NPR', symbol: 'Rs', label: 'Nepalese Rupee' },
];

export const DEFAULT_CURRENCY = CURRENCIES[0];

/** Representative region per currency (unit-system / fallback). */
export const CURRENCY_PRIMARY_REGION = {
  USD: 'US',
  EUR: 'DE',
  GBP: 'GB',
  INR: 'IN',
  AUD: 'AU',
  CAD: 'CA',
  NZD: 'NZ',
  SGD: 'SG',
  HKD: 'HK',
  JPY: 'JP',
  CNY: 'CN',
  KRW: 'KR',
  THB: 'TH',
  MYR: 'MY',
  IDR: 'ID',
  PHP: 'PH',
  VND: 'VN',
  AED: 'AE',
  SAR: 'SA',
  QAR: 'QA',
  KWD: 'KW',
  BHD: 'BH',
  OMR: 'OM',
  ILS: 'IL',
  TRY: 'TR',
  ZAR: 'ZA',
  NGN: 'NG',
  KES: 'KE',
  EGP: 'EG',
  GHS: 'GH',
  MAD: 'MA',
  BRL: 'BR',
  MXN: 'MX',
  ARS: 'AR',
  CLP: 'CL',
  COP: 'CO',
  PEN: 'PE',
  CHF: 'CH',
  SEK: 'SE',
  NOK: 'NO',
  DKK: 'DK',
  PLN: 'PL',
  CZK: 'CZ',
  HUF: 'HU',
  RON: 'RO',
  RUB: 'RU',
  UAH: 'UA',
  TWD: 'TW',
  PKR: 'PK',
  BDT: 'BD',
  LKR: 'LK',
  NPR: 'NP',
};

/**
 * ISO 3166-1 alpha-2 country/region → currency code.
 * Many countries share a currency (e.g. EUR).
 */
export const REGION_CURRENCY = {
  // Americas
  US: 'USD',
  PR: 'USD',
  VI: 'USD',
  GU: 'USD',
  AS: 'USD',
  MP: 'USD',
  CA: 'CAD',
  MX: 'MXN',
  BR: 'BRL',
  AR: 'ARS',
  CL: 'CLP',
  CO: 'COP',
  PE: 'PEN',
  EC: 'USD',
  PA: 'USD',
  SV: 'USD',

  // Europe — Eurozone + nearby
  AT: 'EUR',
  BE: 'EUR',
  CY: 'EUR',
  EE: 'EUR',
  FI: 'EUR',
  FR: 'EUR',
  DE: 'EUR',
  GR: 'EUR',
  IE: 'EUR',
  IT: 'EUR',
  LV: 'EUR',
  LT: 'EUR',
  LU: 'EUR',
  MT: 'EUR',
  NL: 'EUR',
  PT: 'EUR',
  SK: 'EUR',
  SI: 'EUR',
  ES: 'EUR',
  HR: 'EUR',
  AD: 'EUR',
  MC: 'EUR',
  SM: 'EUR',
  VA: 'EUR',
  ME: 'EUR',
  XK: 'EUR',
  GB: 'GBP',
  GG: 'GBP',
  JE: 'GBP',
  IM: 'GBP',
  CH: 'CHF',
  LI: 'CHF',
  SE: 'SEK',
  NO: 'NOK',
  DK: 'DKK',
  FO: 'DKK',
  GL: 'DKK',
  PL: 'PLN',
  CZ: 'CZK',
  HU: 'HUF',
  RO: 'RON',
  RU: 'RUB',
  UA: 'UAH',
  TR: 'TRY',

  // Oceania
  AU: 'AUD',
  NZ: 'NZD',
  CK: 'NZD',
  NU: 'NZD',

  // Asia-Pacific
  IN: 'INR',
  PK: 'PKR',
  BD: 'BDT',
  LK: 'LKR',
  NP: 'NPR',
  SG: 'SGD',
  MY: 'MYR',
  ID: 'IDR',
  PH: 'PHP',
  TH: 'THB',
  VN: 'VND',
  JP: 'JPY',
  CN: 'CNY',
  HK: 'HKD',
  MO: 'HKD',
  TW: 'TWD',
  KR: 'KRW',
  KH: 'USD',
  LA: 'USD',
  MM: 'USD',

  // Middle East
  AE: 'AED',
  SA: 'SAR',
  QA: 'QAR',
  KW: 'KWD',
  BH: 'BHD',
  OM: 'OMR',
  IL: 'ILS',
  JO: 'USD',
  LB: 'USD',
  IQ: 'USD',

  // Africa
  ZA: 'ZAR',
  NG: 'NGN',
  KE: 'KES',
  EG: 'EGP',
  GH: 'GHS',
  MA: 'MAD',
  TZ: 'USD',
  UG: 'USD',
  RW: 'USD',
  ET: 'USD',
};
